---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Install extra packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  when: packages | length > 0

- name: Enable qemu-guest-agent for next boot
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
