---
user_shell: /usr/bin/zsh
ssh_authorized_keys: []

common_packages:
  - git
  - gnupg
  - scdaemon
  - pcscd
  - spice-vdagent
  - qemu-guest-agent
  - zsh
  - curl
  - acl
  - vim
  - xclip
  - fonts-noto-cjk
  - fcitx5
  - fcitx5-hangul
  - pipewire-audio
  - mesa-utils
  - firefox

im_environment:
  - GTK_IM_MODULE=fcitx
  - QT_IM_MODULE=fcitx
  - XMODIFIERS=@im=fcitx
  - SDL_IM_MODULE=fcitx
