---
user_shell: /usr/bin/zsh
ssh_authorized_keys: []
tools: []
desktop: ""
packages: []

common_packages:
  - git
  - gnupg
  - scdaemon
  - pcscd
  - spice-vdagent
  - qemu-guest-agent
  - zsh
  - curl
  - acl
  - vim
